from tests.test_microdot import *  # noqa: F403
from tests.test_multidict import *  # noqa: F403
from tests.test_request import *  # noqa: F403
from tests.test_response import *  # noqa: F403
from tests.test_urlencode import *  # noqa: F403
from tests.test_url_pattern import *  # noqa: F403
from tests.test_websocket import *  # noqa: F403
from tests.test_cors import *  # noqa: F403
from tests.test_utemplate import *  # noqa: F403
from tests.test_session import *  # noqa: F403
